rooms:
  - name: start
    description: Standing at the base of the driveway leading up to the massive mansion, you suddenly realize your knees are shaking.  "Just a little longer," you remind yourself, "all I have to do is get into his office and this will all be over".  You look up at the looming structure ahead of you, take a deep breath, and begin walking.
    initial: true
    doors:
      north:
        description: The driveway leads north up to the mansion
        to: lower driveway
  - name: lower driveway
    description: Only halfway up the long driveway you have to stop to catch your breath.  "If I live through tonight, " you think "I'm finally going to start jogging"
    doors:
      south:
        description: The driveway winds along behind you, eventually leading to the road
        to: start
      north: 
        description: Ahead, the driveway continues meandering toward the mansion.
        to: upper driveway
  - name: upper driveway
    description: Huffing and puffing you finally make it up to the house.  Up close it is even larger and more intimidating than it appeared from the road.  Once more you continue turning back, but unfortunately that has long since ceased to be an option. Steeling yourself, you continue on.
    doors:
      north:
        description: Just ahead of you is the front door
        to: entryway
        locked: true
      south:
        description: Just the thought of that driveway makes your legs ache
        to: lower driveway
      west:
        description: To the west you can see what appears to be a garden
        to: garden
      east:
        description: There appears to be a rather large fountain to the east
        to: fountain
  - name: garden
    description: You find yourself in what used to be a garden, but has since been allowed to become horribly overgrown.  The benches, and even some of the paths have become useless due to the excessive greenery.
    doors:
      east:
        description: To the east is the mansion's main entrance
        to: upper driveway
  - name: fountain
    description: You imagine that this once was a very peaceful spot.  Over time however, the weathering of stone and the tangled overgrowth has given the place a decidedly gloomy appearance.  In truth, you can't wait to leave.
    doors:
      west:
        description: Off to the west, you can see the main entrance
        to: upper driveway
      under:
        description: You see a strangle glinting under a particularly thick mess of brambles.
        to: brambles
        locked: They are much to overgrown to get through.
  - name: brambles
    description: Just for a minute, you curl up here, hidden under the brambles, and think wildly that maybe you can just say here, that maybe it's safe here.  But no, that won't help.  There is no help.
    doors:
      under:
        description: If you slide under the brambles, you can get back to the fountain.
        to: fountain
  - name: entryway
    description: As you enter the once lavish but now crumbling entryway, you hear the front door slam.  Heart thumping, you scrabble for the handle, but encounter only smooth wall.  Slowly regaining your senses, you close your eyes trying to calm the pounding behind your temples.  It looks like theres no turning back, but then there never was.
    doors:
      up:
        description: Ahead of you there appears to be a rather rickety, yet grand, staircase.
        to: stairway
        locked: It appears to be ON FIRE!!!
      west: kitchen
      east: den
  - name: kitchen
    description: You enter a rather ancient looking kitchen.  While the layers upon layers of dust hint at a long period of neglect, yet there is evidence of recent use.
    doors:
      north: laundry
      east: entryway
  - name: laundry
    description: You find an oldstyle laundry room, complete with washbasin and clothesline.
    doors:
      south: kitchen
  - name: den
    description: As you walk through what used to be a rather luxurious den, little puffs of dust rise with each step on the plush carpet.  The moths have long since eaten away the sofa covering, and in fact much of the sofa itself.  Several paintings adorn the wall, but the grime of age is far to thick to make them out.
    doors:
      west: entryway
      north: library
  - name: library
    description: This rather dilapidated library give you the willies, almost more than any other room in the house.  Faceless statues peer out from every corner, giving you the impression of being watched by unseen eyes. The shelves were clearly once lined with books, but only a few covers and pages are even reconizable as such in the overall decay.
    doors:
      south: den
  - name: stairway
    description: You find yourself on a massive curving stairway, lined picture frames you can only assume once held actual paintings.
    doors:
      up:
        description: Above you is an upstairs hallway
        to: upstairs
      down:
        description: At the bottom of the stairs lies the entryway
        to: entryway
  - name: upstairs
    description: As you step into the hallway your heart stops as you hear a loud creak.  Slowly you realize that it was just a loose floorboard.  You suddenly feel very lightheaded.
    doors:
      north:
        to: office
        locked: There appears to be a very angry looking Pit Bull in front of it.
      west: bedroom
      east: nursery
      down:
        description: Below you is the staircase you came up
        to: stairway
  - name: bedroom
    description: A large and intimidating bed dominates the room.  A thick canopy obscures whatever might be inside, and you cannot bring yourself to look.
    doors:
      east: upstairs
  - name: nursery
    description: You find yourself in what appears to have been a nursery.  It is perhaphs the most worn dorn and oppressing room in the house, but the part the really haunts your mind is the ancienct wooden crib in the center of the room, complete with mobile, old holely blankets neatly laid out as though in preporation for an occupant.
    doors:
      west: upstairs
  - name: office
    description: You enter the office, and approach the aged mahogany desk at it's center.  The closer you get the more effort each step seems to take.  With trembling hands you open the top left drawer, and carefully lift out an object wrapped in a black cloth.  You slump into the chair and try to calm your jingling nerves.  It's here... it's all going to be okay.
    victory: true
items:
  - name: pebble
    description: There is a shiny pebble sitting beside the driveway.  As hard as you might try, your eyes are continually drawn to it.  Birdbrain.
    room: lower driveway
  - name: shears
    description: Tangled in some weeds you see a servicable pair of pruning shears.  You hope that spot is rust, you really do.
    room: garden
    used: Sweating and swearing, you manage to cut a useable hole through the brambles
    unlocks:
      room: fountain
      door: under
  - name: key
    description: There appears to be a key laying here
    room: brambles
    used: You unlock the front door to the mansion
    unlocks:
      room: upper driveway
      door: north
  - name: extinguisher
    description: You see and old canister fire extinguisher laying nearby. Hope it still works!
    used: Sure enough, the extinguisher did the job.  If it was the chemical or the copious amounts of dust it sprayed may forever be a mystery.
    room: laundry
    unlocks:
      room: entryway
      door: up
  - name: meat
    description: An unidentified meat is in a lump nearby.
    room: kitchen
    used:  You toss some of the meat to the dog, and it scarfs it down, distracted.  Then it fades out right before your eyes.  Huh, some programmer must be trying to save memory.
    unlocks:
      room: upstairs
      door: north
  - name: poetry
    description: "You see one lone surviving book amongst the ruin.  On the cover you can barely make out the title: Vogon Poetry"
    room: library
